service: lambda-config-demo

plugins:
 - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'ssm:GetParameters'
      Resource: 
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/foo'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/bar'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/jet'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pack'
    - Effect: 'Allow'
      Action: 'kms:Decrypt'    
      Resource: 
        # change this to your KMS key
        - 'arn:aws:kms:us-east-1:#{AWS::AccountId}:key/bf483645-f92d-447f-a18f-7a39fbafdac9'

  # all the functions in the service will get these env variables
  environment:
    foo: foo

functions:
  withEnvVariable:
    handler: functions/withEnvVariable.handler
    environment:
      bar: bar

  withParamStore:
    handler: functions/withParamStore.handler

  withConfigClient:
    handler: functions/withConfigClient.handler